// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class News
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public DateTime PublishDate { get; set; }

    public string Source { get; set; }

    public virtual ICollection<Author> Authors { get; set; } = new List<Author>();

    public virtual ICollection<Link> Links { get; set; } = new List<Link>();
}