--CREATE TABLE [dbo].[NewsAuthors]
--(
--	[Id] INT NOT NULL IDENTITY(1, 1),
--	[NewsId] INT NOT NULL,
--	[AuthorId] INT NOT NULL,
--	CONSTRAINT FK_NewsAuthors_News FOREIGN KEY ([NewsId]) REFERENCES [dbo].[News]([Id]),
--	CONSTRAINT FK_NewsAuthors_Authors FOREIGN KEY ([AuthorId]) REFERENCES [dbo].[Authors]([Id]),
--)
