--CREATE TABLE [dbo].[NewsLinks]
--(
--	[Id] INT NOT NULL IDENTITY(1, 1),
--	[NewsId] INT NOT NULL,
--	[LinkId] INT NOT NULL,
--	CONSTRAINT FK_NewsLinks_News FOREIGN KEY ([NewsId]) REFERENCES [dbo].[News]([Id]),
--	CONSTRAINT FK_NewsLinks_Links FOREIGN KEY ([LinkId]) REFERENCES [dbo].[Links]([Id]),
--)
